sudo: false
language: node_js
os:
  - osx
osx_image:
  - xcode7.3
  - xcode7.2
node_js:
  - 6
  - 4
  - '0.12'
  - '0.10'
addons:
  apt:
    packages: nasm
before_install: if [[ $TRAVIS_OS_NAME == osx ]]; then brew update && brew install nasm autoconf automake libtool; fi;
